WITH MAX_DATA AS
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
            MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE))

# SELECT * FROM MAX_DATA
# SELECT * FROM ECOLI_DATA
# WHERE YEAR(DIFFERENTIATION_DATE) =2019
# SELECT YEAR, MAX_DATA.SIZE_OF_COLONY AS MAXD, ECOLI_DATA.SIZE_OF_COLONY AS ORIGIN, (MAX_DATA.SIZE_OF_COLONY - ECOLI_DATA.SIZE_OF_COLONY) AS YEAR_DEV, ID
SELECT YEAR, (MAX_DATA.SIZE_OF_COLONY - ECOLI_DATA.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA INNER JOIN MAX_DATA  
    ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = MAX_DATA.YEAR
ORDER BY YEAR, YEAR_DEV