SELECT T1.TITLE, T1.BOARD_ID, T2.REPLY_ID, T2.WRITER_ID, T2.CONTENTS, DATE_FORMAT(T2.CREATED_DATE,"%Y-%m-%d") AS CREATED_DATE

FROM USED_GOODS_BOARD AS T1, USED_GOODS_REPLY T2
WHERE T1.CREATED_DATE LIKE "2022-10-%" AND T1.BOARD_ID = T2.BOARD_ID

ORDER BY CREATED_DATE, TITLE 