WITH DEPT_SAL AS (SELECT DEPT_ID, ROUND(AVG(SAL),0) AS AVG_SAL
                    FROM HR_EMPLOYEES
                    GROUP BY DEPT_ID)

SELECT DEPT_SAL.DEPT_ID, TMP.DEPT_NAME_EN, DEPT_SAL.AVG_SAL
FROM HR_DEPARTMENT AS TMP, DEPT_SAL
WHERE TMP.DEPT_ID = DEPT_SAL.DEPT_ID
ORDER BY AVG_SAL DESC